### ISSUE TITLE
Compilation fails on cpphoafparser

### ISSUE THREAD

**Issue by xblahoud** [apirogov/nbautils#1]
Following the steps in README.md, I have the following error.
```
git submodule update --init --recursive --remote
cmake CMakeLists.txt
make
```

```
[  0%] Built target cpphoaf-download
[  5%] Performing update step for 'cpphoafparser'
Error copying directory from "/home/fblahoudek/tools/nbautils/vendor/cpphoafparser-0.99.2-overlay/." to "/home/fblahoudek/tools/nbautils/vendor/cpphoafparser".
make[2]: *** [CMakeFiles/cpphoafparser.dir/build.make:96: vendor/cpphoafparser/src/cpphoafparser-stamp/cpphoafparser-update] Error 1
make[1]: *** [CMakeFiles/Makefile2:137: CMakeFiles/cpphoafparser.dir/all] Error 2
```

**Comment by apirogov** [comment]
I think that CMake changed something regarding the ExternalProject module and the overlay directory does not exist anymore. I removed the corresponding line from the build script and it works again for me. Does it also work for you?

**Comment by xblahoud** [comment]
I can confirm the new version and instructions work for me. Thank you for fixing this.

**Comment by xblahoud** [comment]
I also suggest changing the example in the readme as 
`ltl2tgba -B 'FG b | (FG c & GF a)' | autfilt -DG` creates much smaller automaton than the listed command.

**Comment by apirogov** [comment]
Ah, thanks! I changed it now.
